apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsoor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsoor
    spec:
      containers:
      - name: nsoor
        image: gcr.io/spectral-153422/nsoor:1
        ports:
          - containerPort: 80

        # volumeMounts:
        # - name: vmfs-vmdk-storage
        #   mountPath: /data/
      # volumes:
      # - name: vmfs-vmdk-storage
      #   vsphereVolume:
      #     volumePath: "[Datastore] volumes/testdir"
      #     fsType: ext4
