apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsoor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsoor
    spec:
      containers:
      - name: nsoor
        image: 110723603615.dkr.ecr.us-east-1.amazonaws.com/nsoor:latest
        ports:
          - containerPort: 8080

        # volumeMounts:
        # - name: vmfs-vmdk-storage
        #   mountPath: /data/
      # volumes:
      # - name: vmfs-vmdk-storage
      #   vsphereVolume:
      #     volumePath: "[Datastore] volumes/testdir"
      #     fsType: ext4
