apiVersion: v1
kind: Service
metadata:
  name: nsoor
  namespace: default
  labels:
    app: nsoor
spec:
  selector:
    app: nsoor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
